name: CI
on: [push]
jobs:
  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm i
      - run: npm run prettier:check
      - run: npm run build
